apiVersion: v1
kind: ConfigMap
metadata:
  name: mpp-initializer
data:
  config: |
    podAffinityTerm:
      labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - mpp
        topologyKey: kubernetes.io/hostname
